export const interestTags = [
    'Anime',
    'Manga',
    'Programacion',
    'Gaming',
    'Indie Games',
    'Nintendo',
    'PlayStation',
    'Xbox',
    'PC Gaming',
    'Minecraft',
    'Pokemon',
    'Zelda',
    'Ciencia',
    'Espacio',
    'Astronomia',
    'Fisica',
    'Historia',
    'Filosofia',
    'Psicologia',
    'Naturaleza',
    'Senderismo',
    'Fotografia',
    'Dibujo',
    'Pintura',
    'Diseno',
    'UI Design',
    'Animacion',
    '3D',
    'Blender',
    'Unity',
    'Frontend',
    'Open Source',
    'IA',
    'Cyberseguridad',
    'Linux',
    'Cocina',
    'Cafe',
    'Te',
    'Reposteria',
    'Gatos',
    'Perros',
    'Animales',
    'Musica LoFi',
    'Rock',
    'Metal',
    'Jazz',
    'Piano',
    'Guitarra',
    'K-Pop',
    'Series',
    'Studio Ghibli',
    'Star Wars',
    'Marvel',
    'Harry Potter',
    'Doctor Who',
    'LEGO',
    'Trenes',
    'Mapas',
    'Idiomas',
    'Viajar',
    'Juegos de Mesa',
    'Rol',
    'Dungeons & Dragons',
    'Ajedrez',
    'Coleccionismo',
    'Minimalismo',
    'Meditacion',
    'Espacios Tranquilos',
    'Mascotas',
    'Memes',
    'Podcasts',
    'YouTube',
    'Twitch'
];

export const socialSkillsOptions = [
    { label: 'Prefiero conversaciones profundas', value: 'deep_conversations' },
    { label: 'Tardo en coger confianza', value: 'slow_to_trust' },
    { label: 'Me gustan ambientes tranquilos', value: 'quiet_places' },
    { label: 'Prefiero chat antes que llamadas', value: 'prefer_chat' },
    { label: 'Me cuesta iniciar conversaciones', value: 'hard_to_start_conversations' },
    { label: 'Necesito tiempo para responder', value: 'slow_replies' },
    { label: 'Prefiero grupos pequeños', value: 'small_groups' },
    { label: 'Me gusta escuchar mas que hablar', value: 'listener' },
    { label: 'Disfruto conversaciones largas', value: 'long_conversations' },
    { label: 'Prefiero planes tranquilos', value: 'calm_plans' },
    { label: 'Me agotan los sitios con mucho ruido', value: 'noise_sensitive' },
    { label: 'Prefiero conocer gente poco a poco', value: 'slow_connections' },
    { label: 'Soy mas activo por mensajes', value: 'active_in_chat' },
    { label: 'Me gusta hablar de intereses concretos', value: 'special_interests' },
    { label: 'Prefiero conversaciones claras y directas', value: 'direct_communication' },
    { label: 'Necesito mi espacio personal', value: 'personal_space' },
    { label: 'Me cuesta mantener conversaciones superficiales', value: 'dislike_smalltalk' },
    { label: 'Prefiero quedadas relajadas', value: 'relaxed_meetups' },
    { label: 'A veces desaparezco para recargar energia', value: 'social_recharge' },
    { label: 'Me siento mejor hablando uno a uno', value: 'one_on_one' },
];

export const comfortSkillOptions = [
    { label: 'Sitios tranquilos', value: 'quiet_places' },
    { label: 'Poco ruido', value: 'low_noise' },
    { label: 'Conversaciones claras', value: 'clear_conversations' },
    { label: 'Animales antes que fiestas', value: 'animals_over_parties' },
    { label: 'Lugares con poca gente', value: 'small_crowds' },
    { label: 'Luces suaves', value: 'soft_lighting' },
    { label: 'Planes relajados', value: 'relaxed_plans' },
    { label: 'Tener tiempo para adaptarme', value: 'time_to_adapt' },
    { label: 'Silencio de vez en cuando', value: 'need_silence' },
    { label: 'Espacios ordenados', value: 'organized_spaces' },
    { label: 'Mensajes directos', value: 'direct_messages' },
    { label: 'Rutinas estables', value: 'stable_routines' },
    { label: 'No sentir presion social', value: 'low_social_pressure' },
    { label: 'Poder irme si me saturo', value: 'leave_when_overwhelmed' },
    { label: 'Tiempos de descanso', value: 'rest_time' },
    { label: 'Musica tranquila', value: 'calm_music' },
    { label: 'Paseos tranquilos', value: 'quiet_walks' },
    { label: 'Contacto social poco a poco', value: 'slow_social_contact' },
    { label: 'Hablar de intereses compartidos', value: 'shared_interests' },
    { label: 'Ambientes acogedores', value: 'cozy_spaces' },
];

export const lookingForOptions = [
    { label: 'Amigos para hablar', value: 'friends_to_chat' },
    { label: 'Gente para jugar online', value: 'gaming_friends' },
    { label: 'Planes tranquilos', value: 'calm_plans' },
    { label: 'Conversaciones profundas', value: 'deep_conversations' },
    { label: 'Amistades a largo plazo', value: 'long_term_friendships' },
    { label: 'Gente con intereses similares', value: 'shared_interests' },
    { label: 'Personas para escuchar y ser escuchado', value: 'mutual_support' },
    { label: 'Compañia sin presion', value: 'low_pressure_company' },
    { label: 'Hablar por chat', value: 'chatting' },
    { label: 'Jugar videojuegos juntos', value: 'play_games_together' },
    { label: 'Compartir hobbies', value: 'share_hobbies' },
    { label: 'Conocer gente tranquila', value: 'calm_people' },
    { label: 'Quedar de vez en cuando', value: 'occasional_meetups' },
    { label: 'Amigos para pasear', value: 'walking_friends' },
    { label: 'Personas con las que sentirme comodo', value: 'safe_connections' },
    { label: 'Grupos pequeños', value: 'small_groups' },
    { label: 'Hablar de intereses especiales', value: 'special_interest_talks' },
    { label: 'Conexiones genuinas', value: 'genuine_connections' },
    { label: 'Amigos online', value: 'online_friendships' },
    { label: 'Compartir tiempo tranquilo', value: 'peaceful_time' },
];